### ISSUE TITLE
mapa mental

### ISSUE THREAD

**Issue by QUET012** [SistemasTecTlaxiaco/actividad-4-mapa-mental-QUET012#2]
![1](https://github.com/user-attachments/assets/ecabb538-9ea1-4ac0-ba9a-6fadfbdd26a1)

![2](https://github.com/user-attachments/assets/10b2100d-7c62-4378-80ff-b96f987eb7b1)

**Comment by Ivan-PerezZ** [comment]
Exposición de Ideas Centrales:4/5
Redacción y Ortografía:4/5
Presentación visual:4/5
Referencias:5/5
Calificación Final: 17/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
